# Base URL to work with github pages
baseurl: /Chart.js

repository: nnnick/Chart.js

# Collections of files
collections:
  doc-parts:
    output: false
  doc-parts-v2:
    output: false

markdown: kramdown

future: true
